### ISSUE TITLE
Some confusion in your decisions documents organisation

### ISSUE THREAD

**Issue by dgellow** [alphagov/govuk-aws#94]
Hello there,

I was reading through your [decision documents](https://github.com/alphagov/govuk-aws/tree/master/doc/architecture/decisions) and I found the following mistake:
[ADR 10][adr-10] has a note "Amended by 13. Terraform Data Structure". The actual document is in fact [ADR 15][adr-15]. The text and the link aren't correct.  

Also you seem to have two documents ADR 15: 
- [ADR 15 DNS Infrastructure](https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0015-dns-infrastructure.md), the title is currently "14. DNS Infrastructure", that's confusing because the [ADR 14 is another document](https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0014-launch-config-change-propagation-process.md) 😬.
- [ADR 15 Terraform Data Structure][adr-15] that I mentioned before.

Btw, thank you for sharing publicly those documents 👍

[adr-10]: https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0010-terraform-directory-structure.md
[adr-15]: https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0015-terraform-data-structure.md

**Comment by SamLR** [comment]
Good spot @dgellow, hopefully #95 should sort this out.
